#!/bin/bash
# Version 2
./build && ./install
kpackagetool5 -t Plasma/Applet -u package
plasmoidviewer --applet $(kreadconfig5 --file="$PWD/package/metadata.desktop" --group="Desktop Entry" --key="X-KDE-PluginInfo-Name")
